name = "pelotonic"
compatibility_date = "2026-02-21"
workers_dev = true
preview_urls = true

main = "src/index.ts"

routes = [
  { pattern = "pelotonic.cc/*", zone_name = "pelotonic.cc" },
  { pattern = "www.pelotonic.cc/*", zone_name = "pelotonic.cc" }
]
